name: minds_digital
description: O SDK Flutter da Minds Digital busca proporcionar de forma rápida, simplificada e abstraída as jornadas de autenticação e cadastro por meio da biometria de voz em suas aplicações Flutter.
version: 0.0.5
homepage: https://github.com/mindsdigital/minds-sdk-flutter

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  get_it: ^7.6.0
  record: ^4.4.4
  path_provider: ^2.0.1
  lottie: ^2.4.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  result_dart: ^1.0.5
  equatable: ^2.0.5
  ffmpeg_kit_flutter_full: ^5.1.0-LTS
  uuid: ^3.0.7
  universal_html: ^2.2.3
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.4.2
  build_runner: ^2.1.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
